# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'webRTCtest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for webRTCtest
  pod 'SkyWay'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'
  
end
